In [32]:
import pandas as pd 
import torch
from torch import nn
from torch import utils
from torch.utils.data import DataLoader
import numpy as np
import json
from torch.autograd import Variable
import matplotlib.pyplot as plt
import csv

#Custom weight init
def initi(m):
    if isinstance(m,nn.Linear):
        nn.init.xavier_uniform(m.weight.data)
        

#Simple json load
with open("/Users/abdulsalamyazid/Desktop/Projects/Untitled Folder/train.json") as f:
    train = json.load(f)
        
with open("/Users/abdulsalamyazid/Desktop/Projects/Untitled Folder/test.json") as f:
    test = json.load(f)
    
print ('imported')

imported


In [33]:
from random import shuffle

xx=[d['ingredients'] for d in train]
yy=[d['cuisine'] for d in train]
word_list=set()
for x in xx:
    word_list|=set(tuple(x))
word_list=list(word_list)
#Make the list of cuisines 

cat_list=list(set(yy))

In [34]:
word_list=set()
for x in xx:
    word_list|=set(tuple(x))
word_list=list(word_list)
#Make the list of cuisines 

cat_list=list(set(yy))

In [35]:
newx=[]
for num,rec in enumerate(xx):
    newx.append(np.zeros(len(word_list)))
    for ing in rec:
        if ing in word_list:
            ing_location=word_list.index(ing)
            #newx[num][ing_location]=1/(ing_recep_count[ing_location])
            newx[num][ing_location]=1
newx=np.array(newx)


#Convert the cuisines to numerical representation
newy2=[]
for num,rec in enumerate(yy):
    newy2.append(cat_list.index(rec))
newy2=np.array(newy2)

print ('First 3 recepies of one hot vectors')
print (newx[0:5])

print ('First 5 cuisines in numerical')
print (newy2[0:5])

First 3 recepies of one hot vectors
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
First 5 cuisines in numerical
[ 0 10 17 14 14]


In [36]:

SPLIT = 0.8
#Splitting into training and validation sets with SPLIT amount
tv=int(np.ceil(len(newx)*SPLIT))
xtrain=newx[0:tv]
ytrain=newy2[0:tv]
xval=newx[tv:]
yval=newy2[tv:]

'''
xtrain=newx
ytrain=newy2
'''
print(type(xtrain))

#Convert to tensors and variables
txval= torch.from_numpy(xval)
tyval=torch.from_numpy(yval)
tx= torch.from_numpy(xtrain)
ty=torch.from_numpy(ytrain)
#tx=Variable(loader_train.__iter__().next()[0]).type(dtype)
#tx=tx.cuda()
print (tx.size())
print(len(xtrain))
print(ty[2])


<class 'numpy.ndarray'>
torch.Size([31820, 6714])
31820
tensor(17)


In [37]:
print(xtrain.shape)
print(len(ytrain))

(31820, 6714)
31820


In [38]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader



In [42]:
class  Training_DataSet(Dataset):
    def __init__(self,X,Y,root_dir):
        self.data_features = X
        self.data_target = Y
        self.root_dir = root_dir
        
    def __len__(self):
        return 31820
    
    def __getitem__(self,idx):
        features = self.data_features[idx]  
        target = self.data_target[idx]
        

        
        sample = {"features":features,"target":target}
            
        return sample

In [43]:
transformed_dataset = Training_DataSet(xtrain,
                                       ytrain,
                                       root_dir="/Users/abdulsalamyazid/Desktop/Projects/Kaggle")

In [45]:
for i in range(len(transformed_dataset)):
    sample = transformed_dataset[i]

   # print(i, sample['features'].,sample['target'].size())
    print(i, sample['features'],sample['target'])

    if i == 6:
        break

0 [0. 0. 0. ... 0. 0. 0.] 0
1 [0. 0. 0. ... 0. 0. 0.] 10
2 [0. 0. 0. ... 0. 0. 0.] 17
3 [0. 0. 0. ... 0. 0. 0.] 14
4 [0. 0. 0. ... 0. 0. 0.] 14
5 [0. 0. 0. ... 0. 0. 0.] 6
6 [0. 0. 0. ... 0. 0. 0.] 7
